site_name: PyTorch course
site_url: https://github.com/richarderikjohansson/pytorch

nav:
  - Home: index.md
  - Chapters: 
    - PyTorch Fundamentals: Chapters/00.md
    - PyTorch Workflow Fundamentals: Chapters/01.md
    - PyTorch Neural Network Classification: Chapters/02.md
    - PyTorch Computer Vision: Chapters/03.md
    - PyTorch Custom Datasets: Chapters/04.md
    - PyTorch Going Modular: Chapters/05.md
    - PyTorch Transfer Learning: Chapters/06.md
    - PyTorch Experiment Tracking: Chapters/07.md
    - PyTorch Paper Replicating: Chapters/08.md
    - PyTorch Model Deployment: Chapters/09.md
  - Exercises:
    - PyTorch Fundamentals: Exercises/00.md
    - PyTorch Workflow Fundamentals: Exercises/01.md
  - Models: Models/models.md

theme: 
  name: material
  features:
    - navigation.instant
    - navigation.top
plugins:
  - mkdocstrings:
      handlers:
          python:
            options:
              docstring_style: google 
              docstring_section_style: table
              show_docstring_functions: true
              show_docstring_modules: true
              show_docstring_description: false 
  - search


markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  # 1) Configure MathJax BEFORE loading it
  - javascripts/mathjax-config.js
  # 2) Load MathJax v3
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/richarderikjohansson/pytorch

